# Generated by Django 2.1.7 on 2019-03-31 10:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadQuerys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='StarAmount',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(-5)]),
        ),
    ]
