# Generated by Django 2.1.7 on 2019-03-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyFavourite',
            fields=[
                ('MyFavouriteID', models.AutoField(primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=30)),
                ('Latitude', models.CharField(max_length=30)),
                ('Longitude', models.CharField(max_length=30)),
                ('Introduction', models.TextField()),
            ],
        ),
    ]
